### ISSUE TITLE
Style Suggestion / Improvement

### ISSUE THREAD

**Issue by koufopoulosf** [versatiles-org/versatiles-styles#1]
Hello Team,

I would like to suggest that you should add the water-area layer, above the land-park layer:

![image](https://github.com/versatiles-org/versatiles-styles/assets/66564413/cec1ccf0-698c-4b4c-8ae1-c42eff663b30)

Meaning, there is actually water on that location and it should be visible:

![image](https://github.com/versatiles-org/versatiles-styles/assets/66564413/f0538e20-b5dc-42e2-9f27-9d8c9963750c)

Thank you very much for your time!

**Comment by MichaelKreil** [comment]
Indeed!
![screenshot](https://github.com/versatiles-org/versatiles-styles/assets/1007187/31b87a4a-3d3d-40dc-96d2-4764d25b07df)
VersaTiles: https://tiles.versatiles.org/#16/39.35468/22.92673
OSM: https://www.openstreetmap.org/#map=17/39.35468/22.92673
@yetzt any idea?

**Comment by koufopoulosf** [comment]
Hi guys @MichaelKreil @yetzt, I got an even more important one, let me show you!

**Comment by koufopoulosf** [comment]
![image](https://github.com/versatiles-org/versatiles-styles/assets/66564413/2314160d-f814-43c7-8991-a1cbaa24dbb7)

VersaTiles: https://tiles.versatiles.org/#9.33/37.1691/25.0904
OSM: https://www.openstreetmap.org/#map=10/37.2041/25.0117

**Comment by koufopoulosf** [comment]
![image](https://github.com/versatiles-org/versatiles-styles/assets/66564413/e7767caa-4eea-41c6-a666-183d92938a1d)

VersaTiles: https://tiles.versatiles.org/#13/39.2069/23.9531
OSM: https://www.openstreetmap.org/#map=13/39.2069/23.9531

**Comment by koufopoulosf** [comment]
Thank you for your response @MichaelKreil, I appreciate it. I was about to add the label issue when you replied. By the way, how did you find the place on the map, just from my images? Wow!

I would really appreciate if that issue could be solved. I suppose the issue has something to do with this function here?

https://github.com/versatiles-org/shortbread-tilemaker/blob/f68b9fe0fced9c6b47aecd421e63e95598b7736e/process.lua#L193

Thanks in advance for your time!🙏

**Comment by koufopoulosf** [comment]
@MichaelKreil @yetzt It seems that some places are passed as relations, as opposed to nodes. Run this query:
```
[out:json];
(
  node(39.1189, 23.7174, 39.2047, 23.9451)["place"];
  relation(39.1189, 23.7174, 39.2047, 23.9451)["place"];
);
out center;
```
Here:
https://overpass-turbo.eu/

**Comment by yetzt** [comment]
@koufopoulosf please make one issue per actual problem. it gets super confusing for me otherwise.

**Comment by koufopoulosf** [comment]
@yetzt here is the styles issue where I mention 2 issues. One is for layers that are overlapped by otger layers, while on OSM the style is different, and the other is for the fonts., which are missing on islands (relations with type = multipolygon). That's all.

**Comment by yetzt** [comment]
i've changed the layer order so landuse is rendered below water.

regarding the island labels: those are not a style issue, since the island labels are not present in the vector tiles. this issue has to be raised [upstream](https://github.com/geofabrik/shortbread-tilemaker/).

**Comment by koufopoulosf** [comment]
Thank you very much!
